// The restaurant booking system both spec-driven explainers work on.
// v0 is the starting repo. v1 adds weekend deposits with members exempt (both explainers build the same code).
// v2 adds a free month for new customers, with the grant before the deposit check (plan mode).
// `openspecV2` grants it after the deposit instead, so the first booking still pays.
// All of them pass their tests (5, 9 and 10).

export const code = {
  "v0": {
    "bookings.py": "from dataclasses import dataclass\nfrom datetime import datetime\n\nfrom guests import Guest\n\n\n@dataclass\nclass Booking:\n    guest: Guest\n    start: datetime\n    party_size: int\n\n\ndef book(guest, start, party_size):\n    guest.visits += 1\n    return Booking(guest, start, party_size)",
    "guests.py": "from dataclasses import dataclass\nfrom datetime import date\n\n\n@dataclass\nclass Guest:\n    name: str\n    email: str\n    visits: int = 0\n    member_until: date | None = None\n\n    def is_member(self, on):\n        return self.member_until is not None and on <= self.member_until",
    "payments.py": "# Stand-in for the card payment provider.\ncharges = []\n\n\ndef charge(guest, amount):\n    charges.append((guest.email, amount))",
    "tests/test_bookings.py": "from datetime import date, datetime\n\nfrom bookings import book\nfrom guests import Guest\n\n\ndef test_book_returns_a_booking():\n    guest = Guest(\"Ana\", \"ana@example.com\")\n    booking = book(guest, datetime(2026, 5, 13, 19, 0), 2)\n    assert booking.party_size == 2\n\n\ndef test_membership_lasts_until_its_end_date():\n    guest = Guest(\"Bo\", \"bo@example.com\", member_until=date(2026, 6, 30))\n    assert guest.is_member(date(2026, 6, 30))\n    assert not guest.is_member(date(2026, 7, 1))",
    "README.md": "# Bookings\n\nOnline table bookings for the restaurant. Members of the supper club have a `member_until` date on their guest record.\n\nRun the tests with `python -m pytest`."
  },
  "v1": {
    "bookings.py": "from dataclasses import dataclass\nfrom datetime import datetime\n\nimport payments\nfrom guests import Guest\n\nDEPOSIT_PER_HEAD = 10\nFRIDAY, SATURDAY = 4, 5\n\n\n@dataclass\nclass Booking:\n    guest: Guest\n    start: datetime\n    party_size: int\n    deposit: int = 0\n\n\ndef requires_deposit(guest, booking):\n    if booking.start.weekday() not in (FRIDAY, SATURDAY):\n        return False\n    # Members are exempt\n    if guest.is_member(booking.start.date()):\n        return False\n    return True\n\n\ndef book(guest, start, party_size):\n    guest.visits += 1\n    booking = Booking(guest, start, party_size)\n    if requires_deposit(guest, booking):\n        booking.deposit = DEPOSIT_PER_HEAD * party_size\n        payments.charge(guest, booking.deposit)\n    return booking",
    "guests.py": "from dataclasses import dataclass\nfrom datetime import date\n\n\n@dataclass\nclass Guest:\n    name: str\n    email: str\n    visits: int = 0\n    member_until: date | None = None\n\n    def is_member(self, on):\n        return self.member_until is not None and on <= self.member_until",
    "payments.py": "# Stand-in for the card payment provider.\ncharges = []\n\n\ndef charge(guest, amount):\n    charges.append((guest.email, amount))",
    "tests/test_bookings.py": "from datetime import date, datetime\n\nimport payments\nfrom bookings import book\nfrom guests import Guest\n\nWEDNESDAY_7PM = datetime(2026, 5, 13, 19, 0)\nFRIDAY_7PM = datetime(2026, 5, 15, 19, 0)\n\n\ndef setup_function():\n    payments.charges.clear()\n\n\ndef test_book_returns_a_booking():\n    guest = Guest(\"Ana\", \"ana@example.com\")\n    booking = book(guest, WEDNESDAY_7PM, 2)\n    assert booking.party_size == 2\n\n\ndef test_membership_lasts_until_its_end_date():\n    guest = Guest(\"Bo\", \"bo@example.com\", member_until=date(2026, 6, 30))\n    assert guest.is_member(date(2026, 6, 30))\n    assert not guest.is_member(date(2026, 7, 1))\n\n\ndef test_no_deposit_midweek():\n    booking = book(Guest(\"Ana\", \"ana@example.com\"), WEDNESDAY_7PM, 3)\n    assert booking.deposit == 0\n    assert payments.charges == []\n\n\ndef test_friday_booking_pays_a_deposit_per_head():\n    booking = book(Guest(\"Ana\", \"ana@example.com\"), FRIDAY_7PM, 3)\n    assert booking.deposit == 30\n    assert payments.charges == [(\"ana@example.com\", 30)]\n\n\ndef test_member_pays_no_deposit():\n    guest = Guest(\"Bo\", \"bo@example.com\", member_until=date(2026, 12, 31))\n    booking = book(guest, FRIDAY_7PM, 4)\n    assert booking.deposit == 0\n    assert payments.charges == []",
    "README.md": "# Bookings\n\nOnline table bookings for the restaurant. Members of the supper club have a `member_until` date on their guest record.\n\nRun the tests with `python -m pytest`."
  },
  "v2": {
    "bookings.py": "from dataclasses import dataclass\nfrom datetime import datetime\n\nimport payments\nfrom guests import Guest\n\nDEPOSIT_PER_HEAD = 10\nFRIDAY, SATURDAY = 4, 5\n\n\n@dataclass\nclass Booking:\n    guest: Guest\n    start: datetime\n    party_size: int\n    deposit: int = 0\n\n\ndef requires_deposit(guest, booking):\n    if booking.start.weekday() not in (FRIDAY, SATURDAY):\n        return False\n    # Members are exempt\n    if guest.is_member(booking.start.date()):\n        return False\n    return True\n\n\ndef book(guest, start, party_size):\n    if guest.visits == 0:\n        guest.grant_free_month(start.date())\n    guest.visits += 1\n    booking = Booking(guest, start, party_size)\n    if requires_deposit(guest, booking):\n        booking.deposit = DEPOSIT_PER_HEAD * party_size\n        payments.charge(guest, booking.deposit)\n    return booking",
    "guests.py": "import calendar\nfrom dataclasses import dataclass\nfrom datetime import date\n\n\n@dataclass\nclass Guest:\n    name: str\n    email: str\n    visits: int = 0\n    member_until: date | None = None\n\n    def is_member(self, on):\n        return self.member_until is not None and on <= self.member_until\n\n    def grant_free_month(self, start):\n        year, month = (start.year + 1, 1) if start.month == 12 else (start.year, start.month + 1)\n        day = min(start.day, calendar.monthrange(year, month)[1])\n        end = date(year, month, day)\n        if self.member_until is None or self.member_until < end:\n            self.member_until = end",
    "payments.py": "# Stand-in for the card payment provider.\ncharges = []\n\n\ndef charge(guest, amount):\n    charges.append((guest.email, amount))",
    "tests/test_bookings.py": "from datetime import date, datetime\n\nimport payments\nfrom bookings import book\nfrom guests import Guest\n\nWEDNESDAY_7PM = datetime(2026, 5, 13, 19, 0)\nFRIDAY_7PM = datetime(2026, 5, 15, 19, 0)\n\n\ndef setup_function():\n    payments.charges.clear()\n\n\ndef test_book_returns_a_booking():\n    guest = Guest(\"Ana\", \"ana@example.com\")\n    booking = book(guest, WEDNESDAY_7PM, 2)\n    assert booking.party_size == 2\n\n\ndef test_membership_lasts_until_its_end_date():\n    guest = Guest(\"Bo\", \"bo@example.com\", member_until=date(2026, 6, 30))\n    assert guest.is_member(date(2026, 6, 30))\n    assert not guest.is_member(date(2026, 7, 1))\n\n\ndef test_no_deposit_midweek():\n    booking = book(Guest(\"Ana\", \"ana@example.com\"), WEDNESDAY_7PM, 3)\n    assert booking.deposit == 0\n    assert payments.charges == []\n\n\ndef test_friday_booking_pays_a_deposit_per_head():\n    booking = book(Guest(\"Ana\", \"ana@example.com\", visits=1), FRIDAY_7PM, 3)\n    assert booking.deposit == 30\n    assert payments.charges == [(\"ana@example.com\", 30)]\n\n\ndef test_member_pays_no_deposit():\n    guest = Guest(\"Bo\", \"bo@example.com\", member_until=date(2026, 12, 31))\n    booking = book(guest, FRIDAY_7PM, 4)\n    assert booking.deposit == 0\n    assert payments.charges == []\n\n\ndef test_first_booking_grants_a_free_month():\n    guest = Guest(\"Cy\", \"cy@example.com\")\n    book(guest, WEDNESDAY_7PM, 2)\n    assert guest.member_until == date(2026, 6, 13)\n\n\ndef test_second_booking_does_not_extend_the_month():\n    guest = Guest(\"Cy\", \"cy@example.com\")\n    book(guest, WEDNESDAY_7PM, 2)\n    book(guest, datetime(2026, 5, 20, 19, 0), 2)\n    assert guest.member_until == date(2026, 6, 13)\n\n\ndef test_free_month_is_clamped_to_the_end_of_a_short_month():\n    guest = Guest(\"Cy\", \"cy@example.com\")\n    book(guest, datetime(2026, 1, 31, 19, 0), 2)\n    assert guest.member_until == date(2026, 2, 28)\n\n\ndef test_existing_longer_membership_is_kept():\n    guest = Guest(\"Bo\", \"bo@example.com\", member_until=date(2026, 12, 31))\n    book(guest, WEDNESDAY_7PM, 2)\n    assert guest.member_until == date(2026, 12, 31)",
    "README.md": "# Bookings\n\nOnline table bookings for the restaurant. Members of the supper club have a `member_until` date on their guest record.\n\nRun the tests with `python -m pytest`."
  }
}

/** v2 as the OpenSpec explainer builds it. */
export const openspecV2 = {
  ...code.v2,
  "bookings.py": "from dataclasses import dataclass\nfrom datetime import datetime\n\nimport payments\nfrom guests import Guest\n\nDEPOSIT_PER_HEAD = 10\nFRIDAY, SATURDAY = 4, 5\n\n\n@dataclass\nclass Booking:\n    guest: Guest\n    start: datetime\n    party_size: int\n    deposit: int = 0\n\n\ndef requires_deposit(guest, booking):\n    if booking.start.weekday() not in (FRIDAY, SATURDAY):\n        return False\n    # Members are exempt\n    if guest.is_member(booking.start.date()):\n        return False\n    return True\n\n\ndef book(guest, start, party_size):\n    first_booking = guest.visits == 0\n    guest.visits += 1\n    booking = Booking(guest, start, party_size)\n    if requires_deposit(guest, booking):\n        booking.deposit = DEPOSIT_PER_HEAD * party_size\n        payments.charge(guest, booking.deposit)\n    # The free month starts after the first booking's deposit\n    if first_booking:\n        guest.grant_free_month(start.date())\n    return booking",
  "tests/test_bookings.py": "from datetime import date, datetime\n\nimport payments\nfrom bookings import book\nfrom guests import Guest\n\nWEDNESDAY_7PM = datetime(2026, 5, 13, 19, 0)\nFRIDAY_7PM = datetime(2026, 5, 15, 19, 0)\n\n\ndef setup_function():\n    payments.charges.clear()\n\n\ndef test_book_returns_a_booking():\n    guest = Guest(\"Ana\", \"ana@example.com\")\n    booking = book(guest, WEDNESDAY_7PM, 2)\n    assert booking.party_size == 2\n\n\ndef test_membership_lasts_until_its_end_date():\n    guest = Guest(\"Bo\", \"bo@example.com\", member_until=date(2026, 6, 30))\n    assert guest.is_member(date(2026, 6, 30))\n    assert not guest.is_member(date(2026, 7, 1))\n\n\ndef test_no_deposit_midweek():\n    booking = book(Guest(\"Ana\", \"ana@example.com\"), WEDNESDAY_7PM, 3)\n    assert booking.deposit == 0\n    assert payments.charges == []\n\n\ndef test_friday_booking_pays_a_deposit_per_head():\n    booking = book(Guest(\"Ana\", \"ana@example.com\"), FRIDAY_7PM, 3)\n    assert booking.deposit == 30\n    assert payments.charges == [(\"ana@example.com\", 30)]\n\n\ndef test_member_pays_no_deposit():\n    guest = Guest(\"Bo\", \"bo@example.com\", member_until=date(2026, 12, 31))\n    booking = book(guest, FRIDAY_7PM, 4)\n    assert booking.deposit == 0\n    assert payments.charges == []\n\n\ndef test_first_booking_grants_a_free_month():\n    guest = Guest(\"Cy\", \"cy@example.com\")\n    book(guest, WEDNESDAY_7PM, 2)\n    assert guest.member_until == date(2026, 6, 13)\n\n\ndef test_first_booking_on_a_friday_pays_the_deposit():\n    guest = Guest(\"Cy\", \"cy@example.com\")\n    booking = book(guest, FRIDAY_7PM, 2)\n    assert booking.deposit == 20\n    assert guest.member_until == date(2026, 6, 15)\n\n\ndef test_second_booking_does_not_extend_the_month():\n    guest = Guest(\"Cy\", \"cy@example.com\")\n    book(guest, WEDNESDAY_7PM, 2)\n    book(guest, datetime(2026, 5, 20, 19, 0), 2)\n    assert guest.member_until == date(2026, 6, 13)\n\n\ndef test_free_month_is_clamped_to_the_end_of_a_short_month():\n    guest = Guest(\"Cy\", \"cy@example.com\")\n    book(guest, datetime(2026, 1, 31, 19, 0), 2)\n    assert guest.member_until == date(2026, 2, 28)\n\n\ndef test_existing_longer_membership_is_kept():\n    guest = Guest(\"Bo\", \"bo@example.com\", member_until=date(2026, 12, 31))\n    book(guest, WEDNESDAY_7PM, 2)\n    assert guest.member_until == date(2026, 12, 31)",
};
